/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import persistencia.*;


/**
 *
 * @author unicamp
 */
public class GestaoAcademica extends javax.swing.JFrame {

    DadosPessoas pessoas;
    DadosAluno alunos;
    DadosAlunoGraduacao alunosGrad;
    DadosAlunoPosGraduacao alunosPosGrad;
    DadosCurso cursos;
    DadosCursoGraduacao cursoGrad;
    DadosCursoPosGraduacao cudsoPos;
    DadosDisciplinas disciplinas;
    DadosDisciplinasGraduacao disciplinasGrad;
    DadosDisciplinasPosGraduacao disciplinasPos;
    DadosEquipes equipes;
    DadosFuncionarios funcionarios;
    DadosProfessores professores;
    DadosTecnicos tecnicos;
    /**
     * Creates new form GestaoAcademica
     */
    public GestaoAcademica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        consulta = new javax.swing.JMenu();
        conAcademica = new javax.swing.JMenu();
        conCurso = new javax.swing.JMenu();
        conCursoGrad = new javax.swing.JMenuItem();
        conCursoPosGrad = new javax.swing.JMenuItem();
        conDisciplina = new javax.swing.JMenu();
        conDisciplinaGrad = new javax.swing.JMenuItem();
        conDisciplinaPosGrad = new javax.swing.JMenuItem();
        conEquipe = new javax.swing.JMenuItem();
        conPessoas = new javax.swing.JMenu();
        conAluno = new javax.swing.JMenu();
        conAlunoGrad = new javax.swing.JMenuItem();
        conAlunoPosGrad = new javax.swing.JMenuItem();
        conProfessor = new javax.swing.JMenuItem();
        conTecnico = new javax.swing.JMenuItem();
        cadastro = new javax.swing.JMenu();
        cadAcademico = new javax.swing.JMenu();
        cadCurso = new javax.swing.JMenu();
        cadCursoGrad = new javax.swing.JMenuItem();
        cadCursoPosGrad = new javax.swing.JMenuItem();
        cadDisciplina = new javax.swing.JMenu();
        cadDisciplinaGrad = new javax.swing.JMenuItem();
        cadDisciplinaPosGrad = new javax.swing.JMenuItem();
        cadEquipe = new javax.swing.JMenuItem();
        cadPessoas = new javax.swing.JMenu();
        cadAluno = new javax.swing.JMenu();
        cadAlunoGrad = new javax.swing.JMenuItem();
        cadAlunoPos = new javax.swing.JMenuItem();
        cadFuncionario = new javax.swing.JMenu();
        cadProfessor = new javax.swing.JMenuItem();
        cadTecnico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão Acadêmica");
        setBackground(new java.awt.Color(0, 128, 255));
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        consulta.setText("Consulta");

        conAcademica.setText("Acadêmica");

        conCurso.setText("Curso");

        conCursoGrad.setText("Curso de Graduação");
        conCursoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCursoGradActionPerformed(evt);
            }
        });
        conCurso.add(conCursoGrad);

        conCursoPosGrad.setText("Curso de Pos Graduação");
        conCursoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCursoPosGradActionPerformed(evt);
            }
        });
        conCurso.add(conCursoPosGrad);

        conAcademica.add(conCurso);

        conDisciplina.setText("Disciplina");

        conDisciplinaGrad.setText("Disciplina de Graduação");
        conDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conDisciplinaGradActionPerformed(evt);
            }
        });
        conDisciplina.add(conDisciplinaGrad);

        conDisciplinaPosGrad.setText("Disciplina de Pós Graduação");
        conDisciplinaPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conDisciplinaPosGradActionPerformed(evt);
            }
        });
        conDisciplina.add(conDisciplinaPosGrad);

        conAcademica.add(conDisciplina);

        conEquipe.setText("Equipe");
        conEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conEquipeActionPerformed(evt);
            }
        });
        conAcademica.add(conEquipe);

        consulta.add(conAcademica);

        conPessoas.setText("Pessoas");

        conAluno.setText("Aluno");

        conAlunoGrad.setText("Aluno de Graduação");
        conAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conAlunoGradActionPerformed(evt);
            }
        });
        conAluno.add(conAlunoGrad);

        conAlunoPosGrad.setText("Aluno de Pós Graduação");
        conAlunoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conAlunoPosGradActionPerformed(evt);
            }
        });
        conAluno.add(conAlunoPosGrad);

        conPessoas.add(conAluno);

        conProfessor.setText("Professor");
        conProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conProfessorActionPerformed(evt);
            }
        });
        conPessoas.add(conProfessor);

        conTecnico.setText("Técnico");
        conTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conTecnicoActionPerformed(evt);
            }
        });
        conPessoas.add(conTecnico);

        consulta.add(conPessoas);

        menu.add(consulta);

        cadastro.setText("Cadastro");

        cadAcademico.setText("Acadêmico");

        cadCurso.setText("Curso");

        cadCursoGrad.setText("Curso de Graduação");
        cadCursoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCursoGradActionPerformed(evt);
            }
        });
        cadCurso.add(cadCursoGrad);

        cadCursoPosGrad.setText("Curso de pós Graduação");
        cadCursoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCursoPosGradActionPerformed(evt);
            }
        });
        cadCurso.add(cadCursoPosGrad);

        cadAcademico.add(cadCurso);

        cadDisciplina.setText("Disciplina");

        cadDisciplinaGrad.setText("Disciplina de Graduação");
        cadDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDisciplinaGradActionPerformed(evt);
            }
        });
        cadDisciplina.add(cadDisciplinaGrad);

        cadDisciplinaPosGrad.setText("Disciplina de Pós Graduação");
        cadDisciplinaPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDisciplinaPosGradActionPerformed(evt);
            }
        });
        cadDisciplina.add(cadDisciplinaPosGrad);

        cadAcademico.add(cadDisciplina);

        cadEquipe.setText("Equipe");
        cadEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEquipeActionPerformed(evt);
            }
        });
        cadAcademico.add(cadEquipe);

        cadastro.add(cadAcademico);

        cadPessoas.setText("Pessoas");

        cadAluno.setText("Aluno");

        cadAlunoGrad.setText("Aluno de Graduação");
        cadAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoGradActionPerformed(evt);
            }
        });
        cadAluno.add(cadAlunoGrad);

        cadAlunoPos.setText("Aluno de Pós-Graduação");
        cadAlunoPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoPosActionPerformed(evt);
            }
        });
        cadAluno.add(cadAlunoPos);

        cadPessoas.add(cadAluno);

        cadFuncionario.setText("Funcionário");

        cadProfessor.setText("Professor");
        cadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadProfessorActionPerformed(evt);
            }
        });
        cadFuncionario.add(cadProfessor);

        cadTecnico.setText("Técnico");
        cadTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadTecnicoActionPerformed(evt);
            }
        });
        cadFuncionario.add(cadTecnico);

        cadPessoas.add(cadFuncionario);

        cadastro.add(cadPessoas);

        menu.add(cadastro);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAncestorAdded

    private void conProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conProfessorActionPerformed
        // TODO add your handling code here:
        new TelaConsultarProfessor().setVisible(true);
    }//GEN-LAST:event_conProfessorActionPerformed

    private void conAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conAlunoGradActionPerformed
        // TODO add your handling code here:
        new TelaConsultarAlunoGrad().setVisible(true); 
    }//GEN-LAST:event_conAlunoGradActionPerformed

    private void conCursoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCursoGradActionPerformed
        // TODO add your handling code here:
        new TelaConsultarCursoGrad().setVisible(true); 
    }//GEN-LAST:event_conCursoGradActionPerformed

    private void conDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conDisciplinaGradActionPerformed
        // TODO add your handling code here:
        new TelaConsultarDisciplinaGrad().setVisible(true); 
    }//GEN-LAST:event_conDisciplinaGradActionPerformed

    private void conEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conEquipeActionPerformed
        // TODO add your handling code here:
        new TelaConsultaEquipe().setVisible(true); 
    }//GEN-LAST:event_conEquipeActionPerformed

    private void cadCursoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCursoGradActionPerformed
        // TODO add your handling code here:
        new TelaCadastroCursoGrad().setVisible(true);
    }//GEN-LAST:event_cadCursoGradActionPerformed

    private void cadDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDisciplinaGradActionPerformed
        // TODO add your handling code here:
        new TelaCadastroDisciplinaGrad().setVisible(true);
    }//GEN-LAST:event_cadDisciplinaGradActionPerformed

    private void cadEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEquipeActionPerformed
        // TODO add your handling code here:
        new TelaCadastroEquipe().setVisible(true); 
    }//GEN-LAST:event_cadEquipeActionPerformed

    private void cadAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoGradActionPerformed
        // TODO add your handling code here:
        new TelaCadastroAlunoGrad().setVisible(true);
    }//GEN-LAST:event_cadAlunoGradActionPerformed

    private void cadAlunoPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoPosActionPerformed
        // TODO add your handling code here:
        new TelaCadastroAlunoPosGrad().setVisible(true);
    }//GEN-LAST:event_cadAlunoPosActionPerformed

    private void cadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadProfessorActionPerformed
        // TODO add your handling code here:
        new TelaCadastroProfessor().setVisible(true);
    }//GEN-LAST:event_cadProfessorActionPerformed

    private void cadCursoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCursoPosGradActionPerformed
        // TODO add your handling code here:
        new TelaCadastroCursoPosGrad().setVisible(true);
    }//GEN-LAST:event_cadCursoPosGradActionPerformed

    private void cadDisciplinaPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDisciplinaPosGradActionPerformed
        // TODO add your handling code here:
        new TelaCadastroDisciplinaPosGrad().setVisible(true);
    }//GEN-LAST:event_cadDisciplinaPosGradActionPerformed

    private void conCursoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCursoPosGradActionPerformed
        // TODO add your handling code here:
        new TelaConsultarCursoPosGrad().setVisible(true);
    }//GEN-LAST:event_conCursoPosGradActionPerformed

    private void conAlunoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conAlunoPosGradActionPerformed
        // TODO add your handling code here:
        new TelaConsultarAlunoPosGrad().setVisible(true);
    }//GEN-LAST:event_conAlunoPosGradActionPerformed

    private void conDisciplinaPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conDisciplinaPosGradActionPerformed
        // TODO add your handling code here:
        new TelaConsultarDisciplinaPosGrad().setVisible(true);
    }//GEN-LAST:event_conDisciplinaPosGradActionPerformed

    private void cadTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadTecnicoActionPerformed
        // TODO add your handling code here:
        new TelaCadastroTecnico().setVisible(true);
    }//GEN-LAST:event_cadTecnicoActionPerformed

    private void conTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conTecnicoActionPerformed
        // TODO add your handling code here:
        new TelaConsultarTecnico().setVisible(true);
    }//GEN-LAST:event_conTecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestaoAcademica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadAcademico;
    private javax.swing.JMenu cadAluno;
    private javax.swing.JMenuItem cadAlunoGrad;
    private javax.swing.JMenuItem cadAlunoPos;
    private javax.swing.JMenu cadCurso;
    private javax.swing.JMenuItem cadCursoGrad;
    private javax.swing.JMenuItem cadCursoPosGrad;
    private javax.swing.JMenu cadDisciplina;
    private javax.swing.JMenuItem cadDisciplinaGrad;
    private javax.swing.JMenuItem cadDisciplinaPosGrad;
    private javax.swing.JMenuItem cadEquipe;
    private javax.swing.JMenu cadFuncionario;
    private javax.swing.JMenu cadPessoas;
    private javax.swing.JMenuItem cadProfessor;
    private javax.swing.JMenuItem cadTecnico;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenu conAcademica;
    private javax.swing.JMenu conAluno;
    private javax.swing.JMenuItem conAlunoGrad;
    private javax.swing.JMenuItem conAlunoPosGrad;
    private javax.swing.JMenu conCurso;
    private javax.swing.JMenuItem conCursoGrad;
    private javax.swing.JMenuItem conCursoPosGrad;
    private javax.swing.JMenu conDisciplina;
    private javax.swing.JMenuItem conDisciplinaGrad;
    private javax.swing.JMenuItem conDisciplinaPosGrad;
    private javax.swing.JMenuItem conEquipe;
    private javax.swing.JMenu conPessoas;
    private javax.swing.JMenuItem conProfessor;
    private javax.swing.JMenuItem conTecnico;
    private javax.swing.JMenu consulta;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
} 


