/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import recursosHumanos.*;
import persistencia.*;

import javax.swing.*;

/**
 *
 * @author unicamp
 */
public class TelaConsultarAlunoPosGrad extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaConsultarAlunoPosGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conNomeAlunoPosGrad = new javax.swing.JLabel();
        conCpfAlunoPosGrad = new javax.swing.JLabel();
        conEndAlunoPosGrad = new javax.swing.JLabel();
        conTelAlunoPosGrad = new javax.swing.JLabel();
        cadMatAlunoPosGrad = new javax.swing.JLabel();
        conSitAlunoPosGrad = new javax.swing.JLabel();
        legendaSituacaoAlunoGrad = new javax.swing.JLabel();
        conCurAlunoPosGrad = new javax.swing.JLabel();
        nomeAlunoPosGrad = new javax.swing.JTextField();
        cpfAlunoPosGrad = new javax.swing.JTextField();
        endAlunoPosGrad = new javax.swing.JTextField();
        telAlunoPosGrad = new javax.swing.JTextField();
        matAlunoPosGrad = new javax.swing.JTextField();
        sitAlunoPosGrad = new javax.swing.JTextField();
        curAlunoPosGrad = new javax.swing.JTextField();
        consultarAlunoPosGrad = new javax.swing.JButton();
        conUniAlunoPosGrad = new javax.swing.JLabel();
        uniAlunoPosGrad = new javax.swing.JTextField();
        conAnoIniAlunoPosGrad = new javax.swing.JLabel();
        anoIniAlunoPosGrad = new javax.swing.JTextField();
        conAnoFimAlunoPosGrad = new javax.swing.JLabel();
        anoFimAlunoPosGrad = new javax.swing.JTextField();
        conGradAlunoPosGrad = new javax.swing.JLabel();
        gradAlunoPosGrad = new javax.swing.JTextField();
        limparAlunoPosGrad = new javax.swing.JButton();
        excluirAlunoPosGrad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Aluno de Pós Graduação");

        conNomeAlunoPosGrad.setText("Nome:");

        conCpfAlunoPosGrad.setText("CPF:");

        conEndAlunoPosGrad.setText("Endereço:");

        conTelAlunoPosGrad.setText("Telefone:");

        cadMatAlunoPosGrad.setText("Matricula:");

        conSitAlunoPosGrad.setText("Situação:");

        legendaSituacaoAlunoGrad.setText("(M)atriculado | (T)trancado | (D)esligado");

        conCurAlunoPosGrad.setText("Curso:");

        nomeAlunoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAlunoPosGradActionPerformed(evt);
            }
        });

        sitAlunoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitAlunoPosGradActionPerformed(evt);
            }
        });

        curAlunoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curAlunoPosGradActionPerformed(evt);
            }
        });

        consultarAlunoPosGrad.setText("Buscar");
        consultarAlunoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAlunoPosGradActionPerformed(evt);
            }
        });

        conUniAlunoPosGrad.setText("Universidade:");

        conAnoIniAlunoPosGrad.setText("Ano Ingresso:");

        conAnoFimAlunoPosGrad.setText("Ano Conclusão:");

        conGradAlunoPosGrad.setText("Graduação:");

        limparAlunoPosGrad.setText("Limpar");
        limparAlunoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparAlunoPosGradActionPerformed(evt);
            }
        });

        excluirAlunoPosGrad.setText("Excluir");
        excluirAlunoPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAlunoPosGradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conCpfAlunoPosGrad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conSitAlunoPosGrad)
                                .addGap(18, 18, 18)
                                .addComponent(sitAlunoPosGrad)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(legendaSituacaoAlunoGrad)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(conTelAlunoPosGrad)
                                .addGap(18, 18, 18)
                                .addComponent(telAlunoPosGrad))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadMatAlunoPosGrad)
                        .addGap(7, 7, 7)
                        .addComponent(matAlunoPosGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conAnoIniAlunoPosGrad)
                            .addComponent(conGradAlunoPosGrad))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gradAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conUniAlunoPosGrad)
                                .addGap(18, 18, 18)
                                .addComponent(uniAlunoPosGrad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anoIniAlunoPosGrad, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conAnoFimAlunoPosGrad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anoFimAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conEndAlunoPosGrad)
                        .addGap(18, 18, 18)
                        .addComponent(endAlunoPosGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCurAlunoPosGrad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(curAlunoPosGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conNomeAlunoPosGrad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeAlunoPosGrad))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(consultarAlunoPosGrad)
                                .addGap(18, 18, 18)
                                .addComponent(limparAlunoPosGrad)))
                        .addGap(18, 18, 18)
                        .addComponent(excluirAlunoPosGrad)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadMatAlunoPosGrad)
                    .addComponent(matAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarAlunoPosGrad)
                    .addComponent(limparAlunoPosGrad)
                    .addComponent(excluirAlunoPosGrad))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeAlunoPosGrad)
                    .addComponent(nomeAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCpfAlunoPosGrad)
                    .addComponent(cpfAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conTelAlunoPosGrad)
                    .addComponent(telAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conEndAlunoPosGrad)
                    .addComponent(endAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conSitAlunoPosGrad)
                    .addComponent(sitAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(legendaSituacaoAlunoGrad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCurAlunoPosGrad)
                    .addComponent(curAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conGradAlunoPosGrad)
                    .addComponent(gradAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conUniAlunoPosGrad)
                    .addComponent(uniAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conAnoIniAlunoPosGrad)
                    .addComponent(anoIniAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conAnoFimAlunoPosGrad)
                    .addComponent(anoFimAlunoPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAlunoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAlunoPosGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAlunoPosGradActionPerformed

    private void consultarAlunoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAlunoPosGradActionPerformed
        // TODO add your handling code here:         
        AlunoPosGraduacao alunoPos = DadosAlunoPosGraduacao.buscar(matAlunoPosGrad.getText());
        if (alunoPos == null)
            JOptionPane.showMessageDialog(null,"Aluno não encontrado!");
        else{
            nomeAlunoPosGrad.setText(alunoPos.getNome());
            cpfAlunoPosGrad.setText(alunoPos.getCpf());
            endAlunoPosGrad.setText(alunoPos.getEndereco());
            telAlunoPosGrad.setText(alunoPos.getTelefone());
            matAlunoPosGrad.setText(alunoPos.getMatricula());
            sitAlunoPosGrad.setText(alunoPos.getSituacao());
            curAlunoPosGrad.setText(alunoPos.getCurso().getNome() + " (" + alunoPos.getCurso().getCodigo()+ ")" );
            uniAlunoPosGrad.setText(alunoPos.getUniversidade());
            gradAlunoPosGrad.setText(alunoPos.getGraduacao());
            anoIniAlunoPosGrad.setText(String.valueOf(alunoPos.getAno_inicio()));
            anoFimAlunoPosGrad.setText(String.valueOf(alunoPos.getAno_fim()));
        }
    }//GEN-LAST:event_consultarAlunoPosGradActionPerformed

    private void sitAlunoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitAlunoPosGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitAlunoPosGradActionPerformed

    private void limparAlunoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparAlunoPosGradActionPerformed
        // TODO add your handling code here:
        
        nomeAlunoPosGrad.setText("");
        cpfAlunoPosGrad.setText("");
        endAlunoPosGrad.setText("");
        telAlunoPosGrad.setText("");
        matAlunoPosGrad.setText("");
        sitAlunoPosGrad.setText("");
        curAlunoPosGrad.setText("");
        uniAlunoPosGrad.setText("");
        gradAlunoPosGrad.setText("");
        anoIniAlunoPosGrad.setText("");
        anoFimAlunoPosGrad.setText("");
    }//GEN-LAST:event_limparAlunoPosGradActionPerformed

    private void curAlunoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curAlunoPosGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curAlunoPosGradActionPerformed

    private void excluirAlunoPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAlunoPosGradActionPerformed
        // TODO add your handling code here:
        AlunoPosGraduacao alunoPos;
        alunoPos = DadosAlunoPosGraduacao.buscar(matAlunoPosGrad.getText());
        if (alunoPos == null)
            JOptionPane.showMessageDialog(null,"Aluno não encontrado!");
        else{
            DadosAlunoGraduacao.excluir(matAlunoPosGrad.getText());
            JOptionPane.showMessageDialog(null,"Aluno excluído com sucesso!");
        }
    }//GEN-LAST:event_excluirAlunoPosGradActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoFimAlunoPosGrad;
    private javax.swing.JTextField anoIniAlunoPosGrad;
    private javax.swing.JLabel cadMatAlunoPosGrad;
    private javax.swing.JLabel conAnoFimAlunoPosGrad;
    private javax.swing.JLabel conAnoIniAlunoPosGrad;
    private javax.swing.JLabel conCpfAlunoPosGrad;
    private javax.swing.JLabel conCurAlunoPosGrad;
    private javax.swing.JLabel conEndAlunoPosGrad;
    private javax.swing.JLabel conGradAlunoPosGrad;
    private javax.swing.JLabel conNomeAlunoPosGrad;
    private javax.swing.JLabel conSitAlunoPosGrad;
    private javax.swing.JLabel conTelAlunoPosGrad;
    private javax.swing.JLabel conUniAlunoPosGrad;
    private javax.swing.JButton consultarAlunoPosGrad;
    private javax.swing.JTextField cpfAlunoPosGrad;
    private javax.swing.JTextField curAlunoPosGrad;
    private javax.swing.JTextField endAlunoPosGrad;
    private javax.swing.JButton excluirAlunoPosGrad;
    private javax.swing.JTextField gradAlunoPosGrad;
    private javax.swing.JLabel legendaSituacaoAlunoGrad;
    private javax.swing.JButton limparAlunoPosGrad;
    private javax.swing.JTextField matAlunoPosGrad;
    private javax.swing.JTextField nomeAlunoPosGrad;
    private javax.swing.JTextField sitAlunoPosGrad;
    private javax.swing.JTextField telAlunoPosGrad;
    private javax.swing.JTextField uniAlunoPosGrad;
    // End of variables declaration//GEN-END:variables
}
