/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import academico.*;
import persistencia.*;

import javax.swing.*;


/**
 *
 * @author unicamp
 */
public class TelaConsultarCursoGrad extends javax.swing.JFrame {
    
    boolean teste = false;

    /**
     * Creates new form TelaConsultaEquipe
     */
    
    //DadosCursoGraduacao cursosGraduacao;
    //DadosDisciplinasGraduacao disciplinasGraduacao;
    
    public TelaConsultarCursoGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conNomeCursoGrad = new javax.swing.JLabel();
        conCodCursoGrad = new javax.swing.JLabel();
        conDurCursoGrad = new javax.swing.JLabel();
        nomeCursoGrad = new javax.swing.JTextField();
        codCursoGrad = new javax.swing.JTextField();
        durCursoGrad = new javax.swing.JTextField();
        consultarCursoGrad = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Curso de Graduação");

        conNomeCursoGrad.setText("Nome:");

        conCodCursoGrad.setText("Código:");

        conDurCursoGrad.setText("Duração:");

        nomeCursoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCursoGradActionPerformed(evt);
            }
        });

        consultarCursoGrad.setText("Buscar");
        consultarCursoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCursoGradActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conNomeCursoGrad)
                    .addComponent(conCodCursoGrad)
                    .addComponent(conDurCursoGrad))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeCursoGrad)
                    .addComponent(durCursoGrad)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codCursoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(consultarCursoGrad)
                        .addGap(18, 18, 18)
                        .addComponent(limpar)
                        .addGap(18, 18, 18)
                        .addComponent(excluir)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCodCursoGrad)
                    .addComponent(codCursoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarCursoGrad)
                    .addComponent(limpar)
                    .addComponent(excluir))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeCursoGrad)
                    .addComponent(nomeCursoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conDurCursoGrad)
                    .addComponent(durCursoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCursoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCursoGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCursoGradActionPerformed

    private void consultarCursoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCursoGradActionPerformed
        // TODO add your handling code here:        
        CursoGraduacao cursoGrad = DadosCursoGraduacao.buscar(codCursoGrad.getText());
        if (cursoGrad == null)
            JOptionPane.showMessageDialog(null,"Curso não encontrado!"); 
        else{
            nomeCursoGrad.setText(cursoGrad.getNome());
            durCursoGrad.setText(cursoGrad.getDuracao());
        }
    }//GEN-LAST:event_consultarCursoGradActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        nomeCursoGrad.setText("");
        durCursoGrad.setText("");
        codCursoGrad.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        CursoGraduacao cursoGrad;
        cursoGrad = DadosCursoGraduacao.buscar(codCursoGrad.getText());
        if (cursoGrad == null)
            JOptionPane.showMessageDialog(null,"Curso não encontrado!"); 
        else{
            DadosCursoGraduacao.excluir(codCursoGrad.getText());
        }
    }//GEN-LAST:event_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codCursoGrad;
    private javax.swing.JLabel conCodCursoGrad;
    private javax.swing.JLabel conDurCursoGrad;
    private javax.swing.JLabel conNomeCursoGrad;
    private javax.swing.JButton consultarCursoGrad;
    private javax.swing.JTextField durCursoGrad;
    private javax.swing.JButton excluir;
    private javax.swing.JButton limpar;
    private javax.swing.JButton limparAlunoGrad;
    private javax.swing.JTextField nomeCursoGrad;
    // End of variables declaration//GEN-END:variables
}
