/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import entradas.*;
import recursosHumanos.*;
//import dados.*;
import persistencia.*; 
import javax.swing.JOptionPane;

/**
 *
 * @author unicamp
 */
public class TelaCadastroTecnico extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public TelaCadastroTecnico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadEndTec = new javax.swing.JLabel();
        cadTelTec = new javax.swing.JLabel();
        cadCargoTec = new javax.swing.JLabel();
        cadNomeTec = new javax.swing.JLabel();
        cadCpfTec = new javax.swing.JLabel();
        cadValorHoraExtra = new javax.swing.JLabel();
        cadQtdeHoraExtraTec = new javax.swing.JLabel();
        cadastrarTecnico = new javax.swing.JButton();
        nomeTec = new javax.swing.JTextField();
        cpfTec = new javax.swing.JTextField();
        endTec = new javax.swing.JTextField();
        telTec = new javax.swing.JTextField();
        carTec = new javax.swing.JTextField();
        valHoraExtraTec = new javax.swing.JTextField();
        qtdHoraExtraTec = new javax.swing.JTextField();
        ctpsTec = new javax.swing.JTextField();
        cadCtpsTec = new javax.swing.JLabel();
        depTec = new javax.swing.JTextField();
        cadDepartamentoTec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Professor");

        cadEndTec.setText("Endereço:");

        cadTelTec.setText("Telefone:");

        cadCargoTec.setText("Cargo:");

        cadNomeTec.setText("Nome:");

        cadCpfTec.setText("CPF:");

        cadValorHoraExtra.setText("Valor Hora Extra:");

        cadQtdeHoraExtraTec.setText("Quantidade de Hora Extra:");

        cadastrarTecnico.setText("Cadastrar");
        cadastrarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarTecnicoActionPerformed(evt);
            }
        });

        nomeTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTecActionPerformed(evt);
            }
        });

        cadCtpsTec.setText("CTPS:");

        cadDepartamentoTec.setText("Departamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadDepartamentoTec)
                        .addGap(4, 4, 4)
                        .addComponent(depTec, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarTecnico))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadEndTec)
                            .addComponent(cadCpfTec))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpfTec, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadTelTec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telTec, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(endTec)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadNomeTec)
                        .addGap(30, 30, 30)
                        .addComponent(nomeTec))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadCargoTec)
                                .addGap(4, 4, 4)
                                .addComponent(carTec, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadCtpsTec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctpsTec, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadValorHoraExtra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cadQtdeHoraExtraTec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(qtdHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNomeTec)
                    .addComponent(nomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadCpfTec)
                    .addComponent(cadTelTec)
                    .addComponent(telTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadEndTec)
                    .addComponent(endTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtdHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadQtdeHoraExtraTec))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadValorHoraExtra)
                        .addComponent(valHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadCargoTec)
                        .addComponent(carTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadCtpsTec)
                        .addComponent(ctpsTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cadastrarTecnico))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadDepartamentoTec)
                            .addComponent(depTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarTecnicoActionPerformed
        // TODO add your handling code here:        
        Tecnico tecnico = new Tecnico();                          
    
        if ( tecnico.setNome(nomeTec.getText())      &&
             EntradaDeDados.isCpf(cpfTec.getText())    &&
             tecnico.setEndereco(endTec.getText())   &&
             tecnico.setTelefone(telTec.getText())   &&
             tecnico.setCargo(carTec.getText())   &&
             tecnico.setDepartamento(depTec.getText())   &&
             tecnico.setCtps(ctpsTec.getText()) &&
             tecnico.setQuantidadeHoraExtra(Double.parseDouble((qtdHoraExtraTec.getText())))   &&
             Tecnico.setValorHoraExtra(Double.parseDouble(valHoraExtraTec.getText())))
        { 
            tecnico.setCpf(cpfTec.getText());
            DadosTecnicos.cadastrar(tecnico); 
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!"); 
            nomeTec.setText("");
            cpfTec.setText("");
            endTec.setText("");
            telTec.setText("");
            carTec.setText("");
            depTec.setText("");
            ctpsTec.setText("");
            valHoraExtraTec.setText("");
            qtdHoraExtraTec.setText("");
        }else{
            if (!tecnico.setNome(nomeTec.getText()))
                nomeTec.setText("Entrada Inválida");
            if (!EntradaDeDados.isCpf(cpfTec.getText()))
                cpfTec.setText("CPF Inválido");
            if (!tecnico.setEndereco(endTec.getText()))
                endTec.setText("Entrada Inválida");
            if (!tecnico.setTelefone(telTec.getText()))
                telTec.setText("Entrada Inválida");
            if (!Tecnico.setValorHoraExtra(Double.parseDouble(valHoraExtraTec.getText())))
                valHoraExtraTec.setText("Entrada Inválida");
            if (!tecnico.setQuantidadeHoraExtra(Double.parseDouble((qtdHoraExtraTec.getText()))))
                qtdHoraExtraTec.setText("Entrada Inválida");   
            if (!tecnico.setCargo(carTec.getText()))
                carTec.setText("Entrada Inválida");  
            if (!tecnico.setCtps(ctpsTec.getText()))
                ctpsTec.setText("Entrada Inválida"); 
            if (!tecnico.setDepartamento(depTec.getText()))
                depTec.setText("Entrada Inválida");   
            JOptionPane.showMessageDialog(null,"Itens com entrada iválida. Favor corrigir!");        
        }
        
    }//GEN-LAST:event_cadastrarTecnicoActionPerformed

    private void nomeTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCadastroTecnico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadCargoTec;
    private javax.swing.JLabel cadCpfTec;
    private javax.swing.JLabel cadCtpsTec;
    private javax.swing.JLabel cadDepartamentoTec;
    private javax.swing.JLabel cadEndTec;
    private javax.swing.JLabel cadNomeTec;
    private javax.swing.JLabel cadQtdeHoraExtraTec;
    private javax.swing.JLabel cadTelTec;
    private javax.swing.JLabel cadValorHoraExtra;
    private javax.swing.JButton cadastrarTecnico;
    private javax.swing.JTextField carTec;
    private javax.swing.JTextField cpfTec;
    private javax.swing.JTextField ctpsTec;
    private javax.swing.JTextField depTec;
    private javax.swing.JTextField endTec;
    private javax.swing.JTextField nomeTec;
    private javax.swing.JTextField qtdHoraExtraTec;
    private javax.swing.JTextField telTec;
    private javax.swing.JTextField valHoraExtraTec;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the arePesqProf
     */
    
}
