/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import recursosHumanos.*;
import persistencia.*;

import javax.swing.*;

/**
 *
 * @author unicamp
 */
public class TelaConsultarAlunoGrad extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaConsultarAlunoGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conNomeAlunoGrad = new javax.swing.JLabel();
        conCpfAlunoGrad = new javax.swing.JLabel();
        conEndAlunoGrad = new javax.swing.JLabel();
        conTelAlunoGrad = new javax.swing.JLabel();
        cadMatAlunoGrad = new javax.swing.JLabel();
        conSitAlunoGrad = new javax.swing.JLabel();
        legendaSituacaoAlunoGrad = new javax.swing.JLabel();
        conCurAlunoGrad = new javax.swing.JLabel();
        nomeAlunoGrad = new javax.swing.JTextField();
        cpfAlunoGrad = new javax.swing.JTextField();
        endAlunoGrad = new javax.swing.JTextField();
        telAlunoGrad = new javax.swing.JTextField();
        matAlunoGrad = new javax.swing.JTextField();
        sitAlunoGrad = new javax.swing.JTextField();
        curAlunoGrad = new javax.swing.JTextField();
        consultarAlunoGrad = new javax.swing.JButton();
        limparAlunoGrad = new javax.swing.JButton();
        excluirAlunoGrad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Aluno de Graduação");

        conNomeAlunoGrad.setText("Nome:");

        conCpfAlunoGrad.setText("CPF:");

        conEndAlunoGrad.setText("Endereço:");

        conTelAlunoGrad.setText("Telefone:");

        cadMatAlunoGrad.setText("Matricula:");

        conSitAlunoGrad.setText("Situação:");

        legendaSituacaoAlunoGrad.setText("(M)atriculado | (T)trancado | (D)esligado");

        conCurAlunoGrad.setText("Curso");

        nomeAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAlunoGradActionPerformed(evt);
            }
        });

        sitAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitAlunoGradActionPerformed(evt);
            }
        });

        curAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curAlunoGradActionPerformed(evt);
            }
        });

        consultarAlunoGrad.setText("Buscar");
        consultarAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAlunoGradActionPerformed(evt);
            }
        });

        limparAlunoGrad.setText("Limpar");
        limparAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparAlunoGradActionPerformed(evt);
            }
        });

        excluirAlunoGrad.setText("Excluir");
        excluirAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAlunoGradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(legendaSituacaoAlunoGrad)
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(conNomeAlunoGrad)
                                    .addComponent(conCpfAlunoGrad)
                                    .addComponent(conEndAlunoGrad)
                                    .addComponent(conTelAlunoGrad)
                                    .addComponent(conSitAlunoGrad)
                                    .addComponent(conCurAlunoGrad))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeAlunoGrad)
                                    .addComponent(cpfAlunoGrad)
                                    .addComponent(endAlunoGrad)
                                    .addComponent(telAlunoGrad)
                                    .addComponent(sitAlunoGrad)
                                    .addComponent(curAlunoGrad)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadMatAlunoGrad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(matAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(consultarAlunoGrad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(limparAlunoGrad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(excluirAlunoGrad)
                                .addGap(36, 36, 36)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadMatAlunoGrad)
                    .addComponent(matAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarAlunoGrad)
                    .addComponent(limparAlunoGrad)
                    .addComponent(excluirAlunoGrad))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeAlunoGrad)
                    .addComponent(nomeAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCpfAlunoGrad)
                    .addComponent(cpfAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conEndAlunoGrad)
                    .addComponent(endAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conTelAlunoGrad)
                    .addComponent(telAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conSitAlunoGrad)
                    .addComponent(sitAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legendaSituacaoAlunoGrad)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCurAlunoGrad)
                    .addComponent(curAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAlunoGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAlunoGradActionPerformed

    private void consultarAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAlunoGradActionPerformed
        // TODO add your handling code here:         
        AlunoGraduacao aluno = DadosAlunoGraduacao.buscar(matAlunoGrad.getText());
        if (aluno == null)
            JOptionPane.showMessageDialog(null,"Aluno não encontrado!");
        else{
            nomeAlunoGrad.setText(aluno.getNome());
            cpfAlunoGrad.setText(aluno.getCpf());
            endAlunoGrad.setText(aluno.getEndereco());
            telAlunoGrad.setText(aluno.getTelefone());
            matAlunoGrad.setText(aluno.getMatricula());
            sitAlunoGrad.setText(aluno.getSituacao());
            curAlunoGrad.setText(aluno.getCurso().getNome()+" ("+aluno.getCurso().getCodigo()+")");
        }
    }//GEN-LAST:event_consultarAlunoGradActionPerformed

    private void sitAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitAlunoGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitAlunoGradActionPerformed

    private void limparAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparAlunoGradActionPerformed
        // TODO add your handling code here:

        nomeAlunoGrad.setText("");
        cpfAlunoGrad.setText("");
        endAlunoGrad.setText("");
        telAlunoGrad.setText("");
        matAlunoGrad.setText("");
        sitAlunoGrad.setText("");
        curAlunoGrad.setText("");
    }//GEN-LAST:event_limparAlunoGradActionPerformed

    private void curAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curAlunoGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curAlunoGradActionPerformed

    private void excluirAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAlunoGradActionPerformed
        // TODO add your handling code here:
        AlunoGraduacao aluno;
        aluno = DadosAlunoGraduacao.buscar(matAlunoGrad.getText());
        if (aluno == null)
            JOptionPane.showMessageDialog(null,"Aluno não encontrado!");
        else{
            DadosAlunoGraduacao.excluir(matAlunoGrad.getText());
            JOptionPane.showMessageDialog(null,"Aluno excluído com sucesso!");
        }
    }//GEN-LAST:event_excluirAlunoGradActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadMatAlunoGrad;
    private javax.swing.JLabel conCpfAlunoGrad;
    private javax.swing.JLabel conCurAlunoGrad;
    private javax.swing.JLabel conEndAlunoGrad;
    private javax.swing.JLabel conNomeAlunoGrad;
    private javax.swing.JLabel conSitAlunoGrad;
    private javax.swing.JLabel conTelAlunoGrad;
    private javax.swing.JButton consultarAlunoGrad;
    private javax.swing.JTextField cpfAlunoGrad;
    private javax.swing.JTextField curAlunoGrad;
    private javax.swing.JTextField endAlunoGrad;
    private javax.swing.JButton excluirAlunoGrad;
    private javax.swing.JLabel legendaSituacaoAlunoGrad;
    private javax.swing.JButton limparAlunoGrad;
    private javax.swing.JTextField matAlunoGrad;
    private javax.swing.JTextField nomeAlunoGrad;
    private javax.swing.JTextField sitAlunoGrad;
    private javax.swing.JTextField telAlunoGrad;
    // End of variables declaration//GEN-END:variables
}
