/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import entradas.*;
import recursosHumanos.*;
import persistencia.*; 
import javax.swing.JOptionPane;

/**
 *
 * @author unicamp
 */
public class TelaConsultarProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public TelaConsultarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conEndProf = new javax.swing.JLabel();
        conTelProf = new javax.swing.JLabel();
        conTitProf = new javax.swing.JLabel();
        conAreaPesqProf = new javax.swing.JLabel();
        conNomeProf = new javax.swing.JLabel();
        conCpfProf = new javax.swing.JLabel();
        conNumHorasAula = new javax.swing.JLabel();
        arePesquisaProf = new javax.swing.JTextField();
        nomeProf = new javax.swing.JTextField();
        cpfProf = new javax.swing.JTextField();
        endProf = new javax.swing.JTextField();
        telProf = new javax.swing.JTextField();
        titProf = new javax.swing.JTextField();
        numHorasAulaProf = new javax.swing.JTextField();
        consultarProf = new javax.swing.JButton();
        limparProfessor = new javax.swing.JButton();
        excluirProfessor = new javax.swing.JButton();
        cadValorHoraAula = new javax.swing.JLabel();
        valNumHoraAulaProf = new javax.swing.JTextField();
        ctpsProf = new javax.swing.JTextField();
        conCTPS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Professor");

        conEndProf.setText("Endereço:");

        conTelProf.setText("Telefone:");

        conTitProf.setText("Titulação:");

        conAreaPesqProf.setText("Área de Pesquisa:");

        conNomeProf.setText("Nome:");

        conCpfProf.setText("CPF:");

        conNumHorasAula.setText("Quantidade de Horas Aula:");

        nomeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProfActionPerformed(evt);
            }
        });

        titProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titProfActionPerformed(evt);
            }
        });

        consultarProf.setText("Buscar");
        consultarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProfActionPerformed(evt);
            }
        });

        limparProfessor.setText("Limpar");
        limparProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparProfessorActionPerformed(evt);
            }
        });

        excluirProfessor.setText("Excluir");
        excluirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProfessorActionPerformed(evt);
            }
        });

        cadValorHoraAula.setText("Valor Hora Aula:");

        conCTPS.setText("CTPS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCpfProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfProf, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(consultarProf)
                        .addGap(18, 18, 18)
                        .addComponent(limparProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(excluirProfessor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conAreaPesqProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arePesquisaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conCTPS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctpsProf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conNomeProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeProf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(conEndProf)
                                .addGap(18, 18, 18)
                                .addComponent(endProf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(conTelProf)
                                .addGap(4, 4, 4)
                                .addComponent(telProf, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(conTitProf)
                                .addGap(4, 4, 4)
                                .addComponent(titProf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cadValorHoraAula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valNumHoraAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conNumHorasAula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numHorasAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conCpfProf)
                    .addComponent(consultarProf)
                    .addComponent(limparProfessor)
                    .addComponent(excluirProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeProf)
                    .addComponent(nomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conEndProf)
                    .addComponent(endProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numHorasAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conNumHorasAula)
                    .addComponent(cadValorHoraAula)
                    .addComponent(valNumHoraAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conTitProf)
                    .addComponent(titProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conTelProf)
                    .addComponent(telProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conAreaPesqProf)
                    .addComponent(arePesquisaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conCTPS)
                    .addComponent(ctpsProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProfActionPerformed
        // TODO add your handling code here:
        //new TelaCadastroCursoGrad().setVisible(true);        
        Professor professor = DadosProfessores.buscar(cpfProf.getText());
        
        if ( //EntradaDeDados.isCpf(cpfProf.getText()) &&
             professor != null  ) 
        {            
            nomeProf.setText(professor.getNome());
            endProf.setText(professor.getEndereco());
            telProf.setText(professor.getTelefone());
            titProf.setText(professor.getTitulacao());
            ctpsProf.setText(professor.getCtps());
            valNumHoraAulaProf.setText(String.valueOf(professor.getNumeroHorasAula()));
            arePesquisaProf.setText(professor.getAreaPesquisa());
            numHorasAulaProf.setText(String.valueOf(professor.getNumeroHorasAula()));
        }else{    
            JOptionPane.showMessageDialog(null,"Professor não encontrado!"); 
        }
    }//GEN-LAST:event_consultarProfActionPerformed

    private void nomeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProfActionPerformed

    private void limparProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparProfessorActionPerformed
        // TODO add your handling code here:        
        nomeProf.setText("");
        cpfProf.setText("");
        endProf.setText("");
        telProf.setText("");
        titProf.setText("");
        arePesquisaProf.setText("");
        numHorasAulaProf.setText("");
    }//GEN-LAST:event_limparProfessorActionPerformed

    private void excluirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProfessorActionPerformed
        // TODO add your handling code here:      
        if (DadosProfessores.buscar(cpfProf.getText()) == null  ) 
            JOptionPane.showMessageDialog(null,"Professor não encontrado!"); 
        else
            if (DadosProfessores.excluir(cpfProf.getText()))
                JOptionPane.showMessageDialog(null,"Professor excluído com sucesso!");
    }//GEN-LAST:event_excluirProfessorActionPerformed

    private void titProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arePesquisaProf;
    private javax.swing.JLabel cadValorHoraAula;
    private javax.swing.JLabel conAreaPesqProf;
    private javax.swing.JLabel conCTPS;
    private javax.swing.JLabel conCpfProf;
    private javax.swing.JLabel conEndProf;
    private javax.swing.JLabel conNomeProf;
    private javax.swing.JLabel conNumHorasAula;
    private javax.swing.JLabel conTelProf;
    private javax.swing.JLabel conTitProf;
    private javax.swing.JButton consultarProf;
    private javax.swing.JTextField cpfProf;
    private javax.swing.JTextField ctpsProf;
    private javax.swing.JTextField endProf;
    private javax.swing.JButton excluirProfessor;
    private javax.swing.JButton limparProfessor;
    private javax.swing.JTextField nomeProf;
    private javax.swing.JTextField numHorasAulaProf;
    private javax.swing.JTextField telProf;
    private javax.swing.JTextField titProf;
    private javax.swing.JTextField valNumHoraAulaProf;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the arePesqProf
     */
    public javax.swing.JTextField getArePesqProf() {
        return arePesquisaProf;
    }

    /**
     * @param arePesqProf the arePesqProf to set
     */
    public void setArePesqProf(javax.swing.JTextField arePesqProf) {
        this.arePesquisaProf = arePesqProf;
    }

    /**
     * @return the cadAreaPesqProf
     */
    public javax.swing.JLabel getCadAreaPesqProf() {
        return conAreaPesqProf;
    }

    /**
     * @param cadAreaPesqProf the cadAreaPesqProf to set
     */
    public void setCadAreaPesqProf(javax.swing.JLabel cadAreaPesqProf) {
        this.conAreaPesqProf = cadAreaPesqProf;
    }

    /**
     * @return the cadCpfProf
     */
    public javax.swing.JLabel getCadCpfProf() {
        return conCpfProf;
    }

    /**
     * @param cadCpfProf the cadCpfProf to set
     */
    public void setCadCpfProf(javax.swing.JLabel cadCpfProf) {
        this.conCpfProf = cadCpfProf;
    }

    /**
     * @return the cadEndProf
     */
    public javax.swing.JLabel getCadEndProf() {
        return conEndProf;
    }

    /**
     * @param cadEndProf the cadEndProf to set
     */
    public void setCadEndProf(javax.swing.JLabel cadEndProf) {
        this.conEndProf = cadEndProf;
    }

    /**
     * @return the cadNomeProf
     */
    public javax.swing.JLabel getCadNomeProf() {
        return conNomeProf;
    }

    /**
     * @param cadNomeProf the cadNomeProf to set
     */
    public void setCadNomeProf(javax.swing.JLabel cadNomeProf) {
        this.conNomeProf = cadNomeProf;
    }

    /**
     * @return the cadProf
     */
    public javax.swing.JButton getCadProf() {
        return consultarProf;
    }

    /**
     * @param cadProf the cadProf to set
     */
    public void setCadProf(javax.swing.JButton cadProf) {
        this.consultarProf = cadProf;
    }


    /**
     * @return the cadTelProf
     */
    public javax.swing.JLabel getCadTelProf() {
        return conTelProf;
    }

    /**
     * @param cadTelProf the cadTelProf to set
     */
    public void setCadTelProf(javax.swing.JLabel cadTelProf) {
        this.conTelProf = cadTelProf;
    }

    /**
     * @return the cadTitProf
     */
    public javax.swing.JLabel getCadTitProf() {
        return conTitProf;
    }

    /**
     * @param cadTitProf the cadTitProf to set
     */
    public void setCadTitProf(javax.swing.JLabel cadTitProf) {
        this.conTitProf = cadTitProf;
    }

    /**
     * @return the cpfProf
     */
    public javax.swing.JTextField getCpfProf() {
        return cpfProf;
    }

    /**
     * @param cpfProf the cpfProf to set
     */
    public void setCpfProf(javax.swing.JTextField cpfProf) {
        this.cpfProf = cpfProf;
    }

    /**
     * @return the endProf
     */
    public javax.swing.JTextField getEndProf() {
        return endProf;
    }

    /**
     * @param endProf the endProf to set
     */
    public void setEndProf(javax.swing.JTextField endProf) {
        this.endProf = endProf;
    }

    /**
     * @return the nomeProf
     */
    public javax.swing.JTextField getNomeProf() {
        return nomeProf;
    }

    /**
     * @param nomeProf the nomeProf to set
     */
    public void setNomeProf(javax.swing.JTextField nomeProf) {
        this.nomeProf = nomeProf;
    }

    /**
     * @return the telProf
     */
    public javax.swing.JTextField getTelProf() {
        return telProf;
    }

    /**
     * @param telProf the telProf to set
     */
    public void setTelProf(javax.swing.JTextField telProf) {
        this.telProf = telProf;
    }

    /**
     * @return the titProf
     */
    public javax.swing.JTextField getTitProf() {
        return titProf;
    }

    /**
     * @param titProf the titProf to set
     */
    public void setTitProf(javax.swing.JTextField titProf) {
        this.titProf = titProf;
    }
}
