/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import academico.*;
import persistencia.*;

import javax.swing.*;


/**
 *
 * @author unicamp
 */
public class TelaCadastroCursoGrad extends javax.swing.JFrame {
    
    boolean teste = false;

    /**
     * Creates new form TelaConsultaEquipe
     */
    
    //DadosCursoGraduacao cursosGraduacao;
    //DadosDisciplinasGraduacao disciplinasGraduacao;
    
    public TelaCadastroCursoGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadNomeCursoGrad = new javax.swing.JLabel();
        cadCodCursoGrad = new javax.swing.JLabel();
        cadDurCursoGrad = new javax.swing.JLabel();
        cadDisciplinaCursoGrad = new javax.swing.JLabel();
        nomeCursoGrad = new javax.swing.JTextField();
        codCursoGrad = new javax.swing.JTextField();
        durCursoGrad = new javax.swing.JTextField();
        cadastrarCursoGrad = new javax.swing.JButton();
        cadDisciplinaGrad = new javax.swing.JButton();
        codDisciplinaGrad = new javax.swing.JTextField();
        adicionarDisciplina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Curso de Graduação");

        cadNomeCursoGrad.setText("Nome:");

        cadCodCursoGrad.setText("Código:");

        cadDurCursoGrad.setText("Duração:");

        cadDisciplinaCursoGrad.setText("Disciplinas:");

        nomeCursoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCursoGradActionPerformed(evt);
            }
        });

        cadastrarCursoGrad.setText("Finalizar Cadastro do Curso");
        cadastrarCursoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCursoGradActionPerformed(evt);
            }
        });

        cadDisciplinaGrad.setText("Cadastrar uma nova disciplina");
        cadDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDisciplinaGradActionPerformed(evt);
            }
        });

        codDisciplinaGrad.setText("código da disciplina");

        adicionarDisciplina.setText("Adicionar disciplina ao curso");
        adicionarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadNomeCursoGrad)
                            .addComponent(cadCodCursoGrad)
                            .addComponent(cadDurCursoGrad)
                            .addComponent(cadDisciplinaCursoGrad))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCursoGrad)
                            .addComponent(codCursoGrad)
                            .addComponent(durCursoGrad)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadDisciplinaGrad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(adicionarDisciplina)))
                                .addGap(0, 176, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cadastrarCursoGrad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNomeCursoGrad)
                    .addComponent(nomeCursoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCodCursoGrad)
                    .addComponent(codCursoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadDurCursoGrad)
                    .addComponent(durCursoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadDisciplinaCursoGrad)
                    .addComponent(adicionarDisciplina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadDisciplinaGrad)
                .addGap(33, 33, 33)
                .addComponent(cadastrarCursoGrad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCursoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCursoGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCursoGradActionPerformed

    private void cadastrarCursoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCursoGradActionPerformed
        // TODO add your handling code here:        
        //new TelaCadastroCursoGrad().setVisible(true);
        if (teste)
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!"); 
            nomeCursoGrad.setText("");
            codCursoGrad.setText("");
            durCursoGrad.setText("");
            codDisciplinaGrad.setText("código da disciplina");
    }//GEN-LAST:event_cadastrarCursoGradActionPerformed

    private void cadDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDisciplinaGradActionPerformed
        // TODO add your handling code here:
        new TelaCadastroDisciplinaGrad().setVisible(true);
        //DisciplinaGraduacao disciplinaGrad = new DisciplinaGraduacao();
        
        
    }//GEN-LAST:event_cadDisciplinaGradActionPerformed

    private void adicionarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarDisciplinaActionPerformed
        // TODO add your handling code here:
        CursoGraduacao cursoGrad = new CursoGraduacao(); 
        DisciplinaGraduacao d;
        d = DadosDisciplinasGraduacao.buscar(codDisciplinaGrad.getText());
        if (d == null)
            JOptionPane.showMessageDialog(null,"Disciplina não encontrada"); 
        else{
            if (DadosCursoGraduacao.buscar(codCursoGrad.getText()) == null){
                if (cursoGrad.setNome(nomeCursoGrad.getText())  &&
                    cursoGrad.setCodigo(codCursoGrad.getText()) &&
                    cursoGrad.setDuracao(durCursoGrad.getText())   )
                {            
                    //cursoGrad.setNome(nomeCursoGrad.getText());
                    //cursoGrad.setCodigo(codCursoGrad.getText());
                    //cursoGrad.setDuracao(durCursoGrad.getText());
                    DadosCursoGraduacao.cadastrar(cursoGrad);
                    //cursoGrad.cadastrar(d);
                    //nomeCursoGrad.setText("");
                    //codCursoGrad.setText("");
                    //durCursoGrad.setText(""); 
                    codDisciplinaGrad.setText("código da disciplina");
                    teste = true;
                }
            }
            cursoGrad.cadastrar(d);
            JOptionPane.showMessageDialog(null,"Disciplina adicionada ao curso");
        }
    }//GEN-LAST:event_adicionarDisciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarDisciplina;
    private javax.swing.JLabel cadCodCursoGrad;
    private javax.swing.JLabel cadDisciplinaCursoGrad;
    private javax.swing.JButton cadDisciplinaGrad;
    private javax.swing.JLabel cadDurCursoGrad;
    private javax.swing.JLabel cadNomeCursoGrad;
    private javax.swing.JButton cadastrarCursoGrad;
    private javax.swing.JTextField codCursoGrad;
    private javax.swing.JTextField codDisciplinaGrad;
    private javax.swing.JTextField durCursoGrad;
    private javax.swing.JTextField nomeCursoGrad;
    // End of variables declaration//GEN-END:variables
}
