/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import entradas.*;
import academico.*;
import persistencia.*;

import javax.swing.*;

/**
 *
 * @author unicamp
 */
public class TelaCadastroDisciplinaGrad extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaCadastroDisciplinaGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadNomeDisciplinaGrad = new javax.swing.JLabel();
        cadCodDisciplinaGrad = new javax.swing.JLabel();
        cadCargaHDisciplinaGrad = new javax.swing.JLabel();
        cadCpfProfDisciplinaGrad = new javax.swing.JLabel();
        nomeDisciplinaGrad = new javax.swing.JTextField();
        codDisciplinaGrad = new javax.swing.JTextField();
        cargaHDisciplinaGrad = new javax.swing.JTextField();
        cpfProfDisciplinaGrad = new javax.swing.JTextField();
        cadastrarDisciplinaGrad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Disciplina de Graduação");

        cadNomeDisciplinaGrad.setText("Nome:");

        cadCodDisciplinaGrad.setText("Código:");

        cadCargaHDisciplinaGrad.setText("Carga Horarária:");

        cadCpfProfDisciplinaGrad.setText("Professor:");

        nomeDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDisciplinaGradActionPerformed(evt);
            }
        });

        cpfProfDisciplinaGrad.setText("cpf");
        cpfProfDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfProfDisciplinaGradActionPerformed(evt);
            }
        });

        cadastrarDisciplinaGrad.setText("Finalizar Cadastro da Disciplina");
        cadastrarDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarDisciplinaGradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadCargaHDisciplinaGrad)
                        .addGap(17, 17, 17)
                        .addComponent(cargaHDisciplinaGrad))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cadastrarDisciplinaGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadCpfProfDisciplinaGrad)
                        .addGap(8, 8, 8)
                        .addComponent(cpfProfDisciplinaGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadCodDisciplinaGrad)
                            .addComponent(cadNomeDisciplinaGrad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codDisciplinaGrad)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nomeDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNomeDisciplinaGrad)
                    .addComponent(nomeDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCodDisciplinaGrad)
                    .addComponent(codDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCargaHDisciplinaGrad)
                    .addComponent(cargaHDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCpfProfDisciplinaGrad)
                    .addComponent(cpfProfDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(cadastrarDisciplinaGrad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDisciplinaGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDisciplinaGradActionPerformed

    private void cadastrarDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDisciplinaGradActionPerformed
         // TODO add your handling code here:        
        DisciplinaGraduacao disciplina = new DisciplinaGraduacao();
        
        if (disciplina.setNome(nomeDisciplinaGrad.getText())            &&
            disciplina.setCodigo(codDisciplinaGrad.getText())           &&
            disciplina.setCargaHoraria(cargaHDisciplinaGrad.getText())  &&
            EntradaDeDados.isCpf(cpfProfDisciplinaGrad.getText())       &&
            DadosProfessores.buscar(cpfProfDisciplinaGrad.getText()) != null)
         { 
            disciplina.setProfessor(DadosProfessores.buscar(cpfProfDisciplinaGrad.getText()));
            DadosDisciplinasGraduacao.cadastrar(disciplina);   
            nomeDisciplinaGrad.setText("");
            codDisciplinaGrad.setText("");
            cargaHDisciplinaGrad.setText("");
            cpfProfDisciplinaGrad.setText("cpf");
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!"); 
         }else{        
            if (!disciplina.setNome(nomeDisciplinaGrad.getText()))
                nomeDisciplinaGrad.setText("Entrada Inválida");
            if (!disciplina.setCodigo(codDisciplinaGrad.getText()))
                codDisciplinaGrad.setText("Entrada Inválida");
            if (!disciplina.setCargaHoraria(cargaHDisciplinaGrad.getText()))
                cargaHDisciplinaGrad.setText("Entrada Inválida");
            if (!EntradaDeDados.isCpf(cpfProfDisciplinaGrad.getText()))
                cpfProfDisciplinaGrad.setText("CPF inválido.");
            if (DadosProfessores.buscar(cpfProfDisciplinaGrad.getText()) == null)
                cpfProfDisciplinaGrad.setText("CPF não encontrado.");
            JOptionPane.showMessageDialog(null,"Itens com entrada iválida. Favor corrigir!");
        }
    }//GEN-LAST:event_cadastrarDisciplinaGradActionPerformed

    private void cpfProfDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfProfDisciplinaGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfProfDisciplinaGradActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadCargaHDisciplinaGrad;
    private javax.swing.JLabel cadCodDisciplinaGrad;
    private javax.swing.JLabel cadCpfProfDisciplinaGrad;
    private javax.swing.JLabel cadNomeDisciplinaGrad;
    private javax.swing.JButton cadastrarDisciplinaGrad;
    private javax.swing.JTextField cargaHDisciplinaGrad;
    private javax.swing.JTextField codDisciplinaGrad;
    private javax.swing.JTextField cpfProfDisciplinaGrad;
    private javax.swing.JTextField nomeDisciplinaGrad;
    // End of variables declaration//GEN-END:variables
}
