/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import entradas.*;
import academico.*;
import javax.swing.JOptionPane;
import recursosHumanos.*;
import persistencia.*;

/**
 *
 * @author unicamp
 */
public class TelaCadastroEquipe extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaCadastroEquipe() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpf = new javax.swing.JLabel();
        cpfPesquisador = new javax.swing.JTextField();
        vinculo = new javax.swing.JLabel();
        vinculoPesquisador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        adcionarPesquisador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codEquipe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tituloEquipe = new javax.swing.JTextField();
        cadProfResponsavel = new javax.swing.JLabel();
        cpfProfResponsavel = new javax.swing.JTextField();
        cadastrarEquipe = new javax.swing.JButton();
        cadDataInicio = new javax.swing.JLabel();
        dataInicio = new javax.swing.JTextField();
        cadDataFim = new javax.swing.JLabel();
        dataFim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Equipe");

        cpf.setText("Pesquisador:");

        cpfPesquisador.setText("cpf ou matricula");

        vinculo.setText("Vinculo:");

        vinculoPesquisador.setText("A ou P");

        jLabel1.setText("(A)luno");

        adcionarPesquisador.setText("adicionar à equipe");
        adcionarPesquisador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcionarPesquisadorActionPerformed(evt);
            }
        });

        jLabel2.setText("(P)rofessor");

        jLabel3.setText("Código:");

        jLabel4.setText("Título:");

        cadProfResponsavel.setText("Professor responsável:");

        cadastrarEquipe.setText("Cadastrar");
        cadastrarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEquipeActionPerformed(evt);
            }
        });

        cadDataInicio.setText("Data Inicio:");

        cadDataFim.setText("Data Fim:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloEquipe))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadDataInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataFim))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadProfResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cadastrarEquipe))
                            .addComponent(cpfProfResponsavel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfPesquisador, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vinculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vinculoPesquisador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(adcionarPesquisador)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tituloEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadDataFim)
                        .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadDataInicio)
                        .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadProfResponsavel)
                    .addComponent(cpfProfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(cadastrarEquipe)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpf)
                        .addComponent(cpfPesquisador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vinculoPesquisador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vinculo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(adcionarPesquisador)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adcionarPesquisadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcionarPesquisadorActionPerformed
        // TODO add your handling code here:
        ProjetoDePesquisa equipe;
        //Pesquisador p;
        //p = null;
        equipe = DadosEquipes.buscar(codEquipe.getText());
        if (equipe != null){
            switch (vinculoPesquisador.getText()) {
                case "A":
                    Pesquisador p1 = DadosAluno.buscar(cpfPesquisador.getText());
                    if (p1==null)
                        JOptionPane.showMessageDialog(null,"Pesquisador não encontrado!");
                    else{
                        equipe.cadastrar(p1);
                        JOptionPane.showMessageDialog(null,"Pesquisador cadastrado na equipe!");
                    }
                    break;
                case "P":
                    Pesquisador p2 = DadosProfessores.buscar(cpfPesquisador.getText());
                    if (p2==null)
                        JOptionPane.showMessageDialog(null,"Pesquisador não encontrado!");
                    else{
                        equipe.cadastrar(p2);
                        JOptionPane.showMessageDialog(null,"Pesquisador cadastrado na equipe!");
                    }
                    break;
                default:
                    vinculoPesquisador.setText("Vinculo inválido");
                    break;
            }
            //DadosEquipes.cadastrar(equipe);
        }else
            JOptionPane.showMessageDialog(null,"Equipe não encontrada!");       
    }//GEN-LAST:event_adcionarPesquisadorActionPerformed

    private void cadastrarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEquipeActionPerformed
        // TODO add your handling code here:
        ProjetoDePesquisa equipe = new ProjetoDePesquisa();
        Professor p = null;        
        p = DadosProfessores.buscar(cpfProfResponsavel.getText());
        if (EntradaDeDados.isCpf(cpfProfResponsavel.getText()) &&
            p != null){
            equipe.setProfResponsavel(p);
            equipe.cadastrar(p);
            equipe.setNomeEquipe(tituloEquipe.getText());
            equipe.setCodigo(codEquipe.getText());
            equipe.setDataInicio(Double.valueOf(dataInicio.getText()));  
            equipe.setDataFim(Double.valueOf(dataFim.getText()));
            DadosEquipes.cadastrar(equipe);
            JOptionPane.showMessageDialog(null,"Equipe cadastrada!");
        }
        else 
            JOptionPane.showMessageDialog(null,"Professor não encontrado!");
        
    }//GEN-LAST:event_cadastrarEquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adcionarPesquisador;
    private javax.swing.JLabel cadDataFim;
    private javax.swing.JLabel cadDataInicio;
    private javax.swing.JLabel cadProfResponsavel;
    private javax.swing.JButton cadastrarEquipe;
    private javax.swing.JTextField codEquipe;
    private javax.swing.JLabel cpf;
    private javax.swing.JTextField cpfPesquisador;
    private javax.swing.JTextField cpfProfResponsavel;
    private javax.swing.JTextField dataFim;
    private javax.swing.JTextField dataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tituloEquipe;
    private javax.swing.JLabel vinculo;
    private javax.swing.JTextField vinculoPesquisador;
    // End of variables declaration//GEN-END:variables
}
