/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import academico.*;
import persistencia.*;

import javax.swing.*;

/**
 *
 * @author unicamp
 */
public class TelaConsultarDisciplinaGrad extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaConsultarDisciplinaGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conNomeDisciplinaGrad = new javax.swing.JLabel();
        conCodDisciplinaGrad = new javax.swing.JLabel();
        conCargaHDisciplinaGrad = new javax.swing.JLabel();
        nomeDisciplinaGrad = new javax.swing.JTextField();
        codDisciplinaGrad = new javax.swing.JTextField();
        cargaHDisciplinaGrad = new javax.swing.JTextField();
        consultarDisciplinaGrad = new javax.swing.JButton();
        conCpfProfDisciplinaGrad = new javax.swing.JLabel();
        cpfProfDisciplinaGrad = new javax.swing.JTextField();
        limparDisciplinaGrad = new javax.swing.JButton();
        excluirDisciplinaGrad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Disciplina de Graduação");

        conNomeDisciplinaGrad.setText("Nome:");

        conCodDisciplinaGrad.setText("Código:");

        conCargaHDisciplinaGrad.setText("Carga Horarária:");

        nomeDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDisciplinaGradActionPerformed(evt);
            }
        });

        consultarDisciplinaGrad.setText("Buscar");
        consultarDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDisciplinaGradActionPerformed(evt);
            }
        });

        conCpfProfDisciplinaGrad.setText("Professor:");

        cpfProfDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfProfDisciplinaGradActionPerformed(evt);
            }
        });

        limparDisciplinaGrad.setText("Limpar");
        limparDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDisciplinaGradActionPerformed(evt);
            }
        });

        excluirDisciplinaGrad.setText("Excluir");
        excluirDisciplinaGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirDisciplinaGradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCargaHDisciplinaGrad)
                        .addGap(17, 17, 17)
                        .addComponent(cargaHDisciplinaGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCpfProfDisciplinaGrad)
                        .addGap(8, 8, 8)
                        .addComponent(cpfProfDisciplinaGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conNomeDisciplinaGrad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(nomeDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCodDisciplinaGrad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarDisciplinaGrad)
                        .addGap(18, 18, 18)
                        .addComponent(limparDisciplinaGrad)
                        .addGap(18, 18, 18)
                        .addComponent(excluirDisciplinaGrad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCodDisciplinaGrad)
                    .addComponent(codDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarDisciplinaGrad)
                    .addComponent(limparDisciplinaGrad)
                    .addComponent(excluirDisciplinaGrad))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeDisciplinaGrad)
                    .addComponent(nomeDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCargaHDisciplinaGrad)
                    .addComponent(cargaHDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCpfProfDisciplinaGrad)
                    .addComponent(cpfProfDisciplinaGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDisciplinaGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDisciplinaGradActionPerformed

    private void consultarDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDisciplinaGradActionPerformed
         // TODO add your handling code here:      
        System.out.println("\u000C");  
        DisciplinaGraduacao disciplina = DadosDisciplinasGraduacao.buscar(codDisciplinaGrad.getText());        
        if (disciplina == null)
            JOptionPane.showMessageDialog(null,"Disciplina não encontrada!"); 
        else{        
            nomeDisciplinaGrad.setText(disciplina.getNome());
            cargaHDisciplinaGrad.setText(disciplina.getCargaHoraria());
            cpfProfDisciplinaGrad.setText(disciplina.getProfessor().getNome()); 
        }
    }//GEN-LAST:event_consultarDisciplinaGradActionPerformed

    private void cpfProfDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfProfDisciplinaGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfProfDisciplinaGradActionPerformed

    private void limparDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDisciplinaGradActionPerformed
        // TODO add your handling code here:
            nomeDisciplinaGrad.setText("");
            cargaHDisciplinaGrad.setText("");
            cpfProfDisciplinaGrad.setText(""); 
    }//GEN-LAST:event_limparDisciplinaGradActionPerformed

    private void excluirDisciplinaGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirDisciplinaGradActionPerformed
        // TODO add your handling code here:
        DisciplinaGraduacao disciplinaGrad;
        disciplinaGrad = DadosDisciplinasGraduacao.buscar(codDisciplinaGrad.getText());
        if (disciplinaGrad == null)
            JOptionPane.showMessageDialog(null,"Disciplina não encontrada!");
        else{
            DadosDisciplinasGraduacao.excluir(codDisciplinaGrad.getText());
            JOptionPane.showMessageDialog(null,"Disciplina excluída com sucesso!");
        }
    }//GEN-LAST:event_excluirDisciplinaGradActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cargaHDisciplinaGrad;
    private javax.swing.JTextField codDisciplinaGrad;
    private javax.swing.JLabel conCargaHDisciplinaGrad;
    private javax.swing.JLabel conCodDisciplinaGrad;
    private javax.swing.JLabel conCpfProfDisciplinaGrad;
    private javax.swing.JLabel conNomeDisciplinaGrad;
    private javax.swing.JButton consultarDisciplinaGrad;
    private javax.swing.JTextField cpfProfDisciplinaGrad;
    private javax.swing.JButton excluirDisciplinaGrad;
    private javax.swing.JButton limparDisciplinaGrad;
    private javax.swing.JTextField nomeDisciplinaGrad;
    // End of variables declaration//GEN-END:variables
}
