/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import academico.*;
import persistencia.*;

import javax.swing.*;

/**
 *
 * @author unicamp
 */
public class TelaConsultarDisciplinaPosGrad extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaConsultarDisciplinaPosGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conNomeDisciplinaPosGrad = new javax.swing.JLabel();
        conCodDisciplinaPosGrad = new javax.swing.JLabel();
        conCargaHDisciplinaPosGrad = new javax.swing.JLabel();
        nomeDisciplinaPosGrad = new javax.swing.JTextField();
        codDisciplinaPosGrad = new javax.swing.JTextField();
        cargaHDisciplinaPosGrad = new javax.swing.JTextField();
        consultarDisciplinaPosGrad = new javax.swing.JButton();
        conCpfProfDisciplinaPosGrad = new javax.swing.JLabel();
        cpfProfDisciplinaPosGrad = new javax.swing.JTextField();
        limparDisciplinaPosGrad = new javax.swing.JButton();
        excluirDisciplinaPosGrad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Disciplina de Graduação");

        conNomeDisciplinaPosGrad.setText("Nome:");

        conCodDisciplinaPosGrad.setText("Código:");

        conCargaHDisciplinaPosGrad.setText("Carga Horarária:");

        nomeDisciplinaPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDisciplinaPosGradActionPerformed(evt);
            }
        });

        consultarDisciplinaPosGrad.setText("Buscar");
        consultarDisciplinaPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDisciplinaPosGradActionPerformed(evt);
            }
        });

        conCpfProfDisciplinaPosGrad.setText("Professor:");

        cpfProfDisciplinaPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfProfDisciplinaPosGradActionPerformed(evt);
            }
        });

        limparDisciplinaPosGrad.setText("Limpar");
        limparDisciplinaPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDisciplinaPosGradActionPerformed(evt);
            }
        });

        excluirDisciplinaPosGrad.setText("Excluir");
        excluirDisciplinaPosGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirDisciplinaPosGradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCargaHDisciplinaPosGrad)
                        .addGap(17, 17, 17)
                        .addComponent(cargaHDisciplinaPosGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCpfProfDisciplinaPosGrad)
                        .addGap(8, 8, 8)
                        .addComponent(cpfProfDisciplinaPosGrad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conNomeDisciplinaPosGrad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(nomeDisciplinaPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCodDisciplinaPosGrad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codDisciplinaPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarDisciplinaPosGrad)
                        .addGap(18, 18, 18)
                        .addComponent(limparDisciplinaPosGrad)
                        .addGap(18, 18, 18)
                        .addComponent(excluirDisciplinaPosGrad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCodDisciplinaPosGrad)
                    .addComponent(codDisciplinaPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarDisciplinaPosGrad)
                    .addComponent(limparDisciplinaPosGrad)
                    .addComponent(excluirDisciplinaPosGrad))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeDisciplinaPosGrad)
                    .addComponent(nomeDisciplinaPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCargaHDisciplinaPosGrad)
                    .addComponent(cargaHDisciplinaPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCpfProfDisciplinaPosGrad)
                    .addComponent(cpfProfDisciplinaPosGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDisciplinaPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDisciplinaPosGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDisciplinaPosGradActionPerformed

    private void consultarDisciplinaPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDisciplinaPosGradActionPerformed
         // TODO add your handling code here:      
        System.out.println("\u000C");  
        DisciplinaPosGraduacao disciplinaPos = DadosDisciplinasPosGraduacao.buscar(codDisciplinaPosGrad.getText());        
        if (disciplinaPos == null)
            JOptionPane.showMessageDialog(null,"Disciplina não encontrada!"); 
        else{        
            nomeDisciplinaPosGrad.setText(disciplinaPos.getNome());
            cargaHDisciplinaPosGrad.setText(disciplinaPos.getCargaHoraria());
            cpfProfDisciplinaPosGrad.setText(disciplinaPos.getProfessor().getNome()); 
        }
    }//GEN-LAST:event_consultarDisciplinaPosGradActionPerformed

    private void cpfProfDisciplinaPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfProfDisciplinaPosGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfProfDisciplinaPosGradActionPerformed

    private void limparDisciplinaPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDisciplinaPosGradActionPerformed
        // TODO add your handling code here:
            nomeDisciplinaPosGrad.setText("");
            cargaHDisciplinaPosGrad.setText("");
            cpfProfDisciplinaPosGrad.setText(""); 
    }//GEN-LAST:event_limparDisciplinaPosGradActionPerformed

    private void excluirDisciplinaPosGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirDisciplinaPosGradActionPerformed
        // TODO add your handling code here:
        DisciplinaPosGraduacao disciplinaPosGrad;
        disciplinaPosGrad = DadosDisciplinasPosGraduacao.buscar(codDisciplinaPosGrad.getText());
        if (disciplinaPosGrad == null)
            JOptionPane.showMessageDialog(null,"Disciplina não encontrada!");
        else{
            DadosDisciplinasPosGraduacao.excluir(codDisciplinaPosGrad.getText());
            JOptionPane.showMessageDialog(null,"Disciplina excluída com sucesso!");
        }
    }//GEN-LAST:event_excluirDisciplinaPosGradActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cargaHDisciplinaPosGrad;
    private javax.swing.JTextField codDisciplinaPosGrad;
    private javax.swing.JLabel conCargaHDisciplinaPosGrad;
    private javax.swing.JLabel conCodDisciplinaPosGrad;
    private javax.swing.JLabel conCpfProfDisciplinaPosGrad;
    private javax.swing.JLabel conNomeDisciplinaPosGrad;
    private javax.swing.JButton consultarDisciplinaPosGrad;
    private javax.swing.JTextField cpfProfDisciplinaPosGrad;
    private javax.swing.JButton excluirDisciplinaPosGrad;
    private javax.swing.JButton limparDisciplinaPosGrad;
    private javax.swing.JTextField nomeDisciplinaPosGrad;
    // End of variables declaration//GEN-END:variables
}
