/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import academico.*;
import recursosHumanos.*;
import persistencia.*;

import javax.swing.*;

/**
 *
 * @author unicamp
 */
public class TelaConsultaEquipe extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaConsultaEquipe() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conCpfProfResponsavel = new javax.swing.JLabel();
        cpfProfResponsavel = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        conNomeEquipePesquisa = new javax.swing.JLabel();
        nomeEquipePesquisa = new javax.swing.JTextField();
        conCodEquipe = new javax.swing.JLabel();
        codEquipe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Equipe");

        conCpfProfResponsavel.setText("Professor responsável:");

        consultar.setText("concultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        conNomeEquipePesquisa.setText("Nome Projeto:");

        conCodEquipe.setText("Código Equipe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCodEquipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codEquipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conNomeEquipePesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeEquipePesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conCpfProfResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfProfResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar)
                    .addComponent(excluir)
                    .addComponent(conCodEquipe)
                    .addComponent(codEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeEquipePesquisa)
                    .addComponent(nomeEquipePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCpfProfResponsavel)
                    .addComponent(cpfProfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        ProjetoDePesquisa pp;
        Professor p;
        pp = DadosEquipes.buscar(codEquipe.getText());
        if (pp != null){
            nomeEquipePesquisa.setText(pp.getNomeEquipe());
            p = DadosProfessores.buscar(cpfProfResponsavel.getText());
            cpfProfResponsavel.setText(p.getNome());
        }else{
            JOptionPane.showMessageDialog(null,"Projeto de pesquisa não encontrado!");
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        ProjetoDePesquisa equipe;
        equipe = DadosEquipes.buscar(cpfProfResponsavel.getText());
        if (equipe == null)
            JOptionPane.showMessageDialog(null,"Pesquisador não encontrado!");
        else{
            if (equipe.excluir(cpfProfResponsavel.getText()))
                JOptionPane.showMessageDialog(null,"Excluída com sucesso!");
        }
    }//GEN-LAST:event_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codEquipe;
    private javax.swing.JLabel conCodEquipe;
    private javax.swing.JLabel conCpfProfResponsavel;
    private javax.swing.JLabel conNomeEquipePesquisa;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField cpfProfResponsavel;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField nomeEquipePesquisa;
    // End of variables declaration//GEN-END:variables
}
