/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import entradas.*;
import recursosHumanos.*;
import academico.*;
//import dados.*;
import persistencia.*; 
import javax.swing.JOptionPane;

/**
 *
 * @author unicamp
 */
public class TelaCadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public TelaCadastroProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadEndProf = new javax.swing.JLabel();
        cadTelProf = new javax.swing.JLabel();
        cadTitProf = new javax.swing.JLabel();
        cadAreaPesqProf = new javax.swing.JLabel();
        cadNomeProf = new javax.swing.JLabel();
        cadCpfProf = new javax.swing.JLabel();
        cadValorHoraAula = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cadProf = new javax.swing.JButton();
        arePesquisaProf = new javax.swing.JTextField();
        nomeProf = new javax.swing.JTextField();
        cpfProf = new javax.swing.JTextField();
        endProf = new javax.swing.JTextField();
        telProf = new javax.swing.JTextField();
        titProf = new javax.swing.JTextField();
        valNumHoraAulaProf = new javax.swing.JTextField();
        numHorasAulaProf = new javax.swing.JTextField();
        ctpsProf = new javax.swing.JTextField();
        cadCTPS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Professor");

        cadEndProf.setText("Endereço:");

        cadTelProf.setText("Telefone:");

        cadTitProf.setText("Titulação:");

        cadAreaPesqProf.setText("Área de Pesquisa:");

        cadNomeProf.setText("Nome:");

        cadCpfProf.setText("CPF:");

        cadValorHoraAula.setText("Valor Hora Aula:");

        jLabel1.setText("Quantidade de Horas Aula:");

        cadProf.setText("Cadastrar");
        cadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadProfActionPerformed(evt);
            }
        });

        nomeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProfActionPerformed(evt);
            }
        });

        cadCTPS.setText("CTPS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadValorHoraAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valNumHoraAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numHorasAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadTitProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cadAreaPesqProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arePesquisaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadCTPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctpsProf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadProf))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadEndProf)
                            .addComponent(cadCpfProf))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpfProf, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadTelProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telProf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(endProf)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadNomeProf)
                        .addGap(30, 30, 30)
                        .addComponent(nomeProf)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNomeProf)
                    .addComponent(nomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadCpfProf)
                    .addComponent(cadTelProf)
                    .addComponent(telProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadEndProf)
                    .addComponent(endProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numHorasAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadValorHoraAula)
                        .addComponent(valNumHoraAulaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadTitProf)
                        .addComponent(cadAreaPesqProf)
                        .addComponent(arePesquisaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cadProf))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadCTPS)
                            .addComponent(ctpsProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadProfActionPerformed
        // TODO add your handling code here:
        //new TelaCadastroCursoGrad().setVisible(true);
        
        Professor professor = new Professor();                          
    
        if ( professor.setNome(nomeProf.getText())      &&
             EntradaDeDados.isCpf(cpfProf.getText())    &&
             professor.setEndereco(endProf.getText())   &&
             professor.setTelefone(telProf.getText())   &&
             professor.setTitulacao(titProf.getText())  &&
             professor.setCtps(ctpsProf.getText())      &&
             professor.setAreaPesquisa(arePesquisaProf.getText())   &&
             professor.setValorHoraAula(Double.parseDouble(valNumHoraAulaProf.getText()))   &&
             professor.setNumeroHorasAula(Double.parseDouble((numHorasAulaProf.getText()))))
        { 
            professor.setCpf(cpfProf.getText());
            DadosProfessores.cadastrar(professor); 
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!"); 
            nomeProf.setText("");
            cpfProf.setText("");
            endProf.setText("");
            telProf.setText("");
            titProf.setText("");
            ctpsProf.setText("");
            arePesquisaProf.setText("");
            valNumHoraAulaProf.setText("");
            numHorasAulaProf.setText("");
        }else
        {
            JOptionPane.showMessageDialog(null,"Itens com entrada iválida. Favor corrigir!");
            if (!professor.setNome(nomeProf.getText()))
                arePesquisaProf.setText("Entrada Inválida");
            if (!EntradaDeDados.isCpf(cpfProf.getText()))
                cpfProf.setText("Entrada Inválida");
            if (!professor.setEndereco(endProf.getText()))
                endProf.setText("Entrada Inválida");
            if (!professor.setTelefone(telProf.getText()))
                telProf.setText("Entrada Inválida");
            if (!professor.setTitulacao(titProf.getText()))
                titProf.setText("Entrada Inválida");
            if (!professor.setAreaPesquisa(arePesquisaProf.getText()))
                arePesquisaProf.setText("Entrada Inválida");
            if (!Professor.setValorHoraAula(Double.parseDouble(valNumHoraAulaProf.getText())))
                valNumHoraAulaProf.setText("Entrada Inválida");
            if (!professor.setNumeroHorasAula(Double.parseDouble((numHorasAulaProf.getText()))))
                numHorasAulaProf.setText("Entrada Inválida");                
        }
        
    }//GEN-LAST:event_cadProfActionPerformed

    private void nomeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCadastroProfessor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arePesquisaProf;
    private javax.swing.JLabel cadAreaPesqProf;
    private javax.swing.JLabel cadCTPS;
    private javax.swing.JLabel cadCpfProf;
    private javax.swing.JLabel cadEndProf;
    private javax.swing.JLabel cadNomeProf;
    private javax.swing.JButton cadProf;
    private javax.swing.JLabel cadTelProf;
    private javax.swing.JLabel cadTitProf;
    private javax.swing.JLabel cadValorHoraAula;
    private javax.swing.JTextField cpfProf;
    private javax.swing.JTextField ctpsProf;
    private javax.swing.JTextField endProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomeProf;
    private javax.swing.JTextField numHorasAulaProf;
    private javax.swing.JTextField telProf;
    private javax.swing.JTextField titProf;
    private javax.swing.JTextField valNumHoraAulaProf;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the arePesqProf
     */
    public javax.swing.JTextField getArePesqProf() {
        return arePesquisaProf;
    }

    /**
     * @param arePesqProf the arePesqProf to set
     */
    public void setArePesqProf(javax.swing.JTextField arePesqProf) {
        this.arePesquisaProf = arePesqProf;
    }

    /**
     * @return the cadAreaPesqProf
     */
    public javax.swing.JLabel getCadAreaPesqProf() {
        return cadAreaPesqProf;
    }

    /**
     * @param cadAreaPesqProf the cadAreaPesqProf to set
     */
    public void setCadAreaPesqProf(javax.swing.JLabel cadAreaPesqProf) {
        this.cadAreaPesqProf = cadAreaPesqProf;
    }

    /**
     * @return the cadCpfProf
     */
    public javax.swing.JLabel getCadCpfProf() {
        return cadCpfProf;
    }

    /**
     * @param cadCpfProf the cadCpfProf to set
     */
    public void setCadCpfProf(javax.swing.JLabel cadCpfProf) {
        this.cadCpfProf = cadCpfProf;
    }

    /**
     * @return the cadEndProf
     */
    public javax.swing.JLabel getCadEndProf() {
        return cadEndProf;
    }

    /**
     * @param cadEndProf the cadEndProf to set
     */
    public void setCadEndProf(javax.swing.JLabel cadEndProf) {
        this.cadEndProf = cadEndProf;
    }

    /**
     * @return the cadNomeProf
     */
    public javax.swing.JLabel getCadNomeProf() {
        return cadNomeProf;
    }

    /**
     * @param cadNomeProf the cadNomeProf to set
     */
    public void setCadNomeProf(javax.swing.JLabel cadNomeProf) {
        this.cadNomeProf = cadNomeProf;
    }

    /**
     * @return the cadProf
     */
    public javax.swing.JButton getCadProf() {
        return cadProf;
    }

    /**
     * @param cadProf the cadProf to set
     */
    public void setCadProf(javax.swing.JButton cadProf) {
        this.cadProf = cadProf;
    }


    /**
     * @return the cadTelProf
     */
    public javax.swing.JLabel getCadTelProf() {
        return cadTelProf;
    }

    /**
     * @param cadTelProf the cadTelProf to set
     */
    public void setCadTelProf(javax.swing.JLabel cadTelProf) {
        this.cadTelProf = cadTelProf;
    }

    /**
     * @return the cadTitProf
     */
    public javax.swing.JLabel getCadTitProf() {
        return cadTitProf;
    }

    /**
     * @param cadTitProf the cadTitProf to set
     */
    public void setCadTitProf(javax.swing.JLabel cadTitProf) {
        this.cadTitProf = cadTitProf;
    }

    /**
     * @return the cpfProf
     */
    public javax.swing.JTextField getCpfProf() {
        return cpfProf;
    }

    /**
     * @param cpfProf the cpfProf to set
     */
    public void setCpfProf(javax.swing.JTextField cpfProf) {
        this.cpfProf = cpfProf;
    }

    /**
     * @return the endProf
     */
    public javax.swing.JTextField getEndProf() {
        return endProf;
    }

    /**
     * @param endProf the endProf to set
     */
    public void setEndProf(javax.swing.JTextField endProf) {
        this.endProf = endProf;
    }

    /**
     * @return the nomeProf
     */
    public javax.swing.JTextField getNomeProf() {
        return nomeProf;
    }

    /**
     * @param nomeProf the nomeProf to set
     */
    public void setNomeProf(javax.swing.JTextField nomeProf) {
        this.nomeProf = nomeProf;
    }

    /**
     * @return the telProf
     */
    public javax.swing.JTextField getTelProf() {
        return telProf;
    }

    /**
     * @param telProf the telProf to set
     */
    public void setTelProf(javax.swing.JTextField telProf) {
        this.telProf = telProf;
    }

    /**
     * @return the titProf
     */
    public javax.swing.JTextField getTitProf() {
        return titProf;
    }

    /**
     * @param titProf the titProf to set
     */
    public void setTitProf(javax.swing.JTextField titProf) {
        this.titProf = titProf;
    }
}
