/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import entradas.*;
import recursosHumanos.*;
//import dados.*;
import persistencia.*; 
import javax.swing.JOptionPane;

/**
 *
 * @author unicamp
 */
public class TelaConsultarTecnico extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProfessor
     */
    public TelaConsultarTecnico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conEndTec = new javax.swing.JLabel();
        conTelTec = new javax.swing.JLabel();
        conCargoTec = new javax.swing.JLabel();
        conNomeTec = new javax.swing.JLabel();
        conCpfTec = new javax.swing.JLabel();
        conValorHoraExtra = new javax.swing.JLabel();
        conQtdeHoraExtraTec = new javax.swing.JLabel();
        consultarTecnico = new javax.swing.JButton();
        nomeTec = new javax.swing.JTextField();
        cpfTec = new javax.swing.JTextField();
        endTec = new javax.swing.JTextField();
        telTec = new javax.swing.JTextField();
        carTec = new javax.swing.JTextField();
        valHoraExtraTec = new javax.swing.JTextField();
        qtdHoraExtraTec = new javax.swing.JTextField();
        ctpsTec = new javax.swing.JTextField();
        conCtpsTec = new javax.swing.JLabel();
        depTec = new javax.swing.JTextField();
        conDepartamentoTec = new javax.swing.JLabel();
        limparTecnico = new javax.swing.JButton();
        excluirTecnico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Professor");

        conEndTec.setText("Endereço:");

        conTelTec.setText("Telefone:");

        conCargoTec.setText("Cargo:");

        conNomeTec.setText("Nome:");

        conCpfTec.setText("CPF:");

        conValorHoraExtra.setText("Valor Hora Extra:");

        conQtdeHoraExtraTec.setText("Quantidade de Hora Extra:");

        consultarTecnico.setText("Buscar");
        consultarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTecnicoActionPerformed(evt);
            }
        });

        nomeTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTecActionPerformed(evt);
            }
        });

        conCtpsTec.setText("CTPS:");

        conDepartamentoTec.setText("Departamento:");

        limparTecnico.setText("Limpar");
        limparTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTecnicoActionPerformed(evt);
            }
        });

        excluirTecnico.setText("Excluir");
        excluirTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTecnicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conEndTec)
                        .addGap(4, 4, 4)
                        .addComponent(endTec))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conNomeTec)
                        .addGap(30, 30, 30)
                        .addComponent(nomeTec))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conDepartamentoTec)
                                .addGap(4, 4, 4)
                                .addComponent(depTec, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(conCtpsTec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctpsTec, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conValorHoraExtra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(conQtdeHoraExtraTec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conCpfTec)
                                .addGap(4, 4, 4)
                                .addComponent(cpfTec, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(consultarTecnico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(limparTecnico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(excluirTecnico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conCargoTec)
                                .addGap(4, 4, 4)
                                .addComponent(carTec, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(conTelTec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telTec, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conCpfTec)
                    .addComponent(consultarTecnico)
                    .addComponent(limparTecnico)
                    .addComponent(excluirTecnico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNomeTec)
                    .addComponent(nomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conTelTec)
                    .addComponent(telTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conCargoTec)
                    .addComponent(carTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conEndTec)
                    .addComponent(endTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtdHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conQtdeHoraExtraTec))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(conValorHoraExtra)
                        .addComponent(valHoraExtraTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conCtpsTec)
                    .addComponent(ctpsTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conDepartamentoTec)
                    .addComponent(depTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTecnicoActionPerformed
        // TODO add your handling code here:        
        Tecnico tecnico;
        tecnico = DadosTecnicos.buscar(cpfTec.getText());
        if (tecnico == null)
            JOptionPane.showMessageDialog(null,"Técnico não encontrado!");
        else{
            nomeTec.setText(tecnico.getNome());
            endTec.setText(tecnico.getEndereco());
            telTec.setText(tecnico.getTelefone());
            carTec.setText(tecnico.getCargo());
            depTec.setText(tecnico.getDepartamento());
            ctpsTec.setText(tecnico.getCtps());
            valHoraExtraTec.setText(String.valueOf(tecnico.getQuantidadeHoraExtra()));
            qtdHoraExtraTec.setText(String.valueOf(tecnico.getValorHoraExtra()));
        }
        
    }//GEN-LAST:event_consultarTecnicoActionPerformed

    private void nomeTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTecActionPerformed

    private void limparTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTecnicoActionPerformed
        // TODO add your handling code here:
        endTec.setText("");
        nomeTec.setText("");
        endTec.setText("");
        telTec.setText("");
        carTec.setText("");
        depTec.setText("");
        valHoraExtraTec.setText("");
        qtdHoraExtraTec.setText("");
        
    }//GEN-LAST:event_limparTecnicoActionPerformed

    private void excluirTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirTecnicoActionPerformed
        // TODO add your handling code here:
        if (DadosTecnicos.buscar(cpfTec.getText()) == null  )
            JOptionPane.showMessageDialog(null,"Técnico não encontrado!");
        else{
            if (DadosTecnicos.excluir(cpfTec.getText()))
                JOptionPane.showMessageDialog(null,"Técnico excluído com sucesso!");
                endTec.setText("");
                nomeTec.setText("");
                endTec.setText("");
                telTec.setText("");
                carTec.setText("");
                depTec.setText("");
                valHoraExtraTec.setText("");
                qtdHoraExtraTec.setText("");                
        }
    }//GEN-LAST:event_excluirTecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaConsultarTecnico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carTec;
    private javax.swing.JLabel conCargoTec;
    private javax.swing.JLabel conCpfTec;
    private javax.swing.JLabel conCtpsTec;
    private javax.swing.JLabel conDepartamentoTec;
    private javax.swing.JLabel conEndTec;
    private javax.swing.JLabel conNomeTec;
    private javax.swing.JLabel conQtdeHoraExtraTec;
    private javax.swing.JLabel conTelTec;
    private javax.swing.JLabel conValorHoraExtra;
    private javax.swing.JButton consultarTecnico;
    private javax.swing.JTextField cpfTec;
    private javax.swing.JTextField ctpsTec;
    private javax.swing.JTextField depTec;
    private javax.swing.JTextField endTec;
    private javax.swing.JButton excluirTecnico;
    private javax.swing.JButton limparTecnico;
    private javax.swing.JTextField nomeTec;
    private javax.swing.JTextField qtdHoraExtraTec;
    private javax.swing.JTextField telTec;
    private javax.swing.JTextField valHoraExtraTec;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the arePesqProf
     */
    
}
