/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;
import entradas.*;
import recursosHumanos.*;
import persistencia.*;

import javax.swing.*;

/**
 *
 * @author unicamp
 */
public class TelaCadastroAlunoGrad extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEquipe
     */
    public TelaCadastroAlunoGrad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadNomeAlunoGrad = new javax.swing.JLabel();
        cadCpfAlunoGrad = new javax.swing.JLabel();
        cadEndAlunoGrad = new javax.swing.JLabel();
        cadTelAlunoGrad = new javax.swing.JLabel();
        cadMatAlunoGrad = new javax.swing.JLabel();
        cadSitAlunoGrad = new javax.swing.JLabel();
        legendaSituacaoAlunoGrad = new javax.swing.JLabel();
        cadCurAlunoGrad = new javax.swing.JLabel();
        nomeAlunoGrad = new javax.swing.JTextField();
        cpfAlunoGrad = new javax.swing.JTextField();
        endAlunoGrad = new javax.swing.JTextField();
        telAlunoGrad = new javax.swing.JTextField();
        matAlunoGrad = new javax.swing.JTextField();
        sitAlunoGrad = new javax.swing.JTextField();
        curAlunoGrad = new javax.swing.JTextField();
        cadastrarAlunoGrad = new javax.swing.JButton();
        cadCursoAlunoGrad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Aluno de Graduação");

        cadNomeAlunoGrad.setText("Nome:");

        cadCpfAlunoGrad.setText("CPF:");

        cadEndAlunoGrad.setText("Endereço:");

        cadTelAlunoGrad.setText("Telefone:");

        cadMatAlunoGrad.setText("Matricula:");

        cadSitAlunoGrad.setText("Situação:");

        legendaSituacaoAlunoGrad.setText("(M)atriculado | (T)trancado | (D)esligado");

        cadCurAlunoGrad.setText("Curso");

        nomeAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAlunoGradActionPerformed(evt);
            }
        });

        sitAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitAlunoGradActionPerformed(evt);
            }
        });

        curAlunoGrad.setText("código");

        cadastrarAlunoGrad.setText("Finalizar Cadastro");
        cadastrarAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoGradActionPerformed(evt);
            }
        });

        cadCursoAlunoGrad.setText("Cadastrar novo curso");
        cadCursoAlunoGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCursoAlunoGradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 186, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(legendaSituacaoAlunoGrad)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cadastrarAlunoGrad)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadNomeAlunoGrad)
                            .addComponent(cadCpfAlunoGrad)
                            .addComponent(cadEndAlunoGrad)
                            .addComponent(cadTelAlunoGrad)
                            .addComponent(cadMatAlunoGrad)
                            .addComponent(cadSitAlunoGrad)
                            .addComponent(cadCurAlunoGrad))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeAlunoGrad)
                            .addComponent(cpfAlunoGrad)
                            .addComponent(endAlunoGrad)
                            .addComponent(telAlunoGrad)
                            .addComponent(matAlunoGrad)
                            .addComponent(sitAlunoGrad)
                            .addComponent(curAlunoGrad))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadCursoAlunoGrad)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNomeAlunoGrad)
                    .addComponent(nomeAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCpfAlunoGrad)
                    .addComponent(cpfAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadEndAlunoGrad)
                    .addComponent(endAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadTelAlunoGrad)
                    .addComponent(telAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadMatAlunoGrad)
                    .addComponent(matAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadSitAlunoGrad)
                    .addComponent(sitAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legendaSituacaoAlunoGrad)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCurAlunoGrad)
                    .addComponent(curAlunoGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadCursoAlunoGrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(cadastrarAlunoGrad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAlunoGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAlunoGradActionPerformed

    private void cadastrarAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoGradActionPerformed
        // TODO add your handling code here:  
        System.out.println("\u000C");
        AlunoGraduacao alunoGrad = new AlunoGraduacao(); 
        
        if ( alunoGrad.setNome(nomeAlunoGrad.getText())          &&
             EntradaDeDados.isCpf(cpfAlunoGrad.getText())        &&
             alunoGrad.setCpf(cpfAlunoGrad.getText())            &&
             alunoGrad.setEndereco(endAlunoGrad.getText())       &&
             alunoGrad.setTelefone(telAlunoGrad.getText())       &&
             alunoGrad.setMatricula(matAlunoGrad.getText())      &&
             alunoGrad.setSituacao(sitAlunoGrad.getText())       &&
             DadosCursoGraduacao.buscar(curAlunoGrad.getText()) !=  null)
        {
            alunoGrad.setCursoGraduacao(DadosCursoGraduacao.buscar(curAlunoGrad.getText()));
            DadosAlunoGraduacao.cadastrar(alunoGrad); 
            nomeAlunoGrad.setText("");
            cpfAlunoGrad.setText("");
            endAlunoGrad.setText("");
            telAlunoGrad.setText("");
            matAlunoGrad.setText("");
            sitAlunoGrad.setText("");
            curAlunoGrad.setText("cod");  
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!");         
        }else{
            JOptionPane.showMessageDialog(null,"Itens com entrada iválida. Favor corrigir!");
            //new TelaErro().setVisible(true);
            
            if (!alunoGrad.setNome(nomeAlunoGrad.getText()))
                nomeAlunoGrad.setText("Entrada Inválida");
            if (!EntradaDeDados.isCpf(cpfAlunoGrad.getText()))
                cpfAlunoGrad.setText("Entrada Inválida");
            if (!alunoGrad.setEndereco(endAlunoGrad.getText()))
                endAlunoGrad.setText("Entrada Inválida");
            if (!alunoGrad.setTelefone(telAlunoGrad.getText()))
                telAlunoGrad.setText("Entrada Inválida");
            if (!alunoGrad.setMatricula(matAlunoGrad.getText()))
                matAlunoGrad.setText("Entrada Inválida");
            if (!alunoGrad.setSituacao(sitAlunoGrad.getText()))
                sitAlunoGrad.setText("Entrada Inválida");
            if (DadosCursoGraduacao.buscar(curAlunoGrad.getText()) ==  null)
                curAlunoGrad.setText("Curso " + curAlunoGrad.getText() + " não encontrado.");
        }        
    }//GEN-LAST:event_cadastrarAlunoGradActionPerformed

    private void cadCursoAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCursoAlunoGradActionPerformed
        // TODO add your handling code here: 
        System.out.println("\u000C");
        new TelaCadastroCursoGrad().setVisible(true);
    }//GEN-LAST:event_cadCursoAlunoGradActionPerformed

    private void sitAlunoGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitAlunoGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitAlunoGradActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadCpfAlunoGrad;
    private javax.swing.JLabel cadCurAlunoGrad;
    private javax.swing.JButton cadCursoAlunoGrad;
    private javax.swing.JLabel cadEndAlunoGrad;
    private javax.swing.JLabel cadMatAlunoGrad;
    private javax.swing.JLabel cadNomeAlunoGrad;
    private javax.swing.JLabel cadSitAlunoGrad;
    private javax.swing.JLabel cadTelAlunoGrad;
    private javax.swing.JButton cadastrarAlunoGrad;
    private javax.swing.JTextField cpfAlunoGrad;
    private javax.swing.JTextField curAlunoGrad;
    private javax.swing.JTextField endAlunoGrad;
    private javax.swing.JLabel legendaSituacaoAlunoGrad;
    private javax.swing.JTextField matAlunoGrad;
    private javax.swing.JTextField nomeAlunoGrad;
    private javax.swing.JTextField sitAlunoGrad;
    private javax.swing.JTextField telAlunoGrad;
    // End of variables declaration//GEN-END:variables
}
